apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: shopnow-product-sa
      containers:
        - name: product-service
          image: cedrick13bienvenue/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: PORT_PRODUCT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_NAME_PRODUCTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopnow-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopnow-secret
                  key: JWT_SECRET
            - name: S3_BUCKET
              value: "shopnow-product-images-cedrick"
            - name: AWS_REGION
              value: "eu-west-1"
            - name: CLOUDFRONT_DOMAIN
              value: "d2zhph5qkh6hqt.cloudfront.net"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
