apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: shopnow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: shopnow-ebs
  resources:
    requests:
      storage: 1Gi
