apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cedrick13bienvenue/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: PORT_ORDER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: DB_NAME_ORDERS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopnow-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopnow-secret
                  key: JWT_SECRET
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: CART_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopnow-config
                  key: PRODUCT_SERVICE_URL
